# -*- coding: utf-8 -*-
"""NeuroDTMF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1luHX1l7fEuF0G3oqXKgjgC5Ms5Po8h_T
"""

import tensorflow as tf
from tensorflow.keras import layers, models,Input
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
import numpy as np
import pandas as pd
from google.colab import drive
import os
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix

#On monte le drive
drive.mount("/content/drive")

print(os.listdir("/content/drive/MyDrive"))

print(os.listdir("/content/drive/MyDrive/datasets"))

#on attribut le lien de notre fichier zip
zip_path = "/content/drive/MyDrive/datasets/dataset_spectrogram.zip"
!unzip -oq "$zip_path" -d "/content/dataset"
path_url ="/content/dataset/dataset_spectrogram"
classes = os.listdir(path_url)
print(f"classes detectées {classes}")

#verification de chaque sous dossier
for c in classes:
    path = f"{path_url}/{c}"
    print(c, ":", len(os.listdir(path)))

data = []

for label in classes:
    class_path = os.path.join(path_url, label)

    for file in os.listdir(class_path):
        data.append((os.path.join(class_path, file), label))


df = pd.DataFrame(data, columns=["filepath", "label"])

print(f"Total images :{len(df)}")
print(df.head())

train_df, temp_df = train_test_split(
    df,
    test_size=0.3,
    stratify=df["label"],
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,
    stratify=temp_df["label"],
    random_state=42
)

print(f"Train: {len(train_df)} | Val: {len(val_df)} | Test: {len(test_df)}")

train_df["label"].value_counts(normalize=True)
val_df["label"].value_counts(normalize=True)
test_df["label"].value_counts(normalize=True)

class_names = sorted(df["label"].unique())
label_to_index = {name: i for i, name in enumerate(class_names)}

train_df["label"] = train_df["label"].map(label_to_index)
val_df["label"] = val_df["label"].map(label_to_index)
test_df["label"] = test_df["label"].map(label_to_index)

import matplotlib.pyplot as plt
import cv2

# afficher quelques images
sample = train_df.sample(9, random_state=42)

plt.figure(figsize=(10,10))

for i, (idx, row) in enumerate(sample.iterrows()):
    img = cv2.imread(row["filepath"], cv2.IMREAD_GRAYSCALE)

    plt.subplot(3,3,i+1)
    plt.imshow(img, cmap='gray')
    plt.title(f"Label: {row['label']}")
    plt.axis('off')

plt.tight_layout()
plt.show()

train_datagen = ImageDataGenerator()

val_datagen = ImageDataGenerator()

IMG_SIZE = (128, 128)
BATCH_SIZE = 32

train_generator = train_datagen.flow_from_dataframe(
    dataframe=train_df,
    x_col='filepath',
    y_col='label',
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='sparse'
)

val_generator = val_datagen.flow_from_dataframe(
    dataframe=val_df,
    x_col='filepath',
    y_col='label',
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='sparse',
    shuffle=False
)

def build_final_baseline():
  model=models.Sequential([

      Input(shape=(128,128,3)),

      layers.Conv2D(32,(3,3),activation = 'relu',padding = 'same'),
      layers.BatchNormalization(),
      layers.MaxPooling2D((2,2)),

      layers.Conv2D(64,(3,3),activation='relu',padding = 'same'),
      layers.BatchNormalization(),
      layers.MaxPooling2D((2,2)),


      layers.Conv2D(128,(3,3),activation='relu',padding='same'),
      layers.BatchNormalization(),
      layers.MaxPooling2D((2,2)),

      layers.Flatten(),

      layers.Dense(256,activation='relu'),
      layers.BatchNormalization(),
      layers.Dropout(0.4),

      layers.Dense(16,activation='softmax')
  ])

  optimizer = tf.keras.optimizers.Adam(learning_rate = 1e-3)

  model.compile(
      optimizer=optimizer,
      loss='sparse_categorical_crossentropy',
      metrics=['accuracy']
  )
  return model




cnn_model = build_final_baseline()

cnn_model.summary()



print("Train samples :", train_generator.samples)
print("Batch size :", train_generator.batch_size)
print("Steps per epoch :", len(train_generator))

print("Validation samples :", val_generator.samples)
print("Validation steps :", len(val_generator))




early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True,
    verbose=1
)

checkpoint = ModelCheckpoint(
    "best_model.keras",
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)

callbacks_list = [early_stop, checkpoint]




history = cnn_model.fit(

    train_generator,

    # Keras calcule automatiquement les steps
    steps_per_epoch=len(train_generator),

    epochs=25,

    validation_data=val_generator,

    validation_steps=len(val_generator),

    callbacks=callbacks_list)